name: Create country file
on:
  workflow_dispatch:
    inputs:
      fileName:
        description: "Country file name"
        required: true
        type: string
      countryName:
        description: "Country name"
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create country file
        run: |
          cd src/pages
          echo "# ${{ inputs.countryName }}" >> "${{ inputs.fileName }}.mdx"
          cd ../../

      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Create country file" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
